version: "3"
services:
  mongo:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodata:/data/db
  growthbook:
    image: "growthbook/growthbook:latest"
    ports:
    - "4000:3000" # example: use 4000 instead of 3000 for the app
    - "4100:3100" # example: use 4100 instead of 3100 for the api
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://root:password@mongo:27017/growthbook?authSource=admin
      - APP_ORIGIN=https://growth.sangletech.com
      - API_HOST=https://growth-api.sangletech.com
      - EMAIL_ENABLED=true
      - EMAIL_HOST=smtp.resend.com
      - EMAIL_PORT=25
      - EMAIL_HOST_USER=resend
      - EMAIL_HOST_PASSWORD=re_gSa1Yt6B_9y8ywTiRvnuAtzHYekLGhBhd
      - EMAIL_FROM=smartie@sangletech.com
      - JWT_SECRET=y5GkFw6Qu03xY78E5ABegZH92CaYKcyeO86uotXw2VSe-3SWSxjelIbmOSR7LL50LhcuYi5UY9YD0ZxDYkzvSg
    volumes:
      - uploads:/usr/local/src/app/packages/back-end/uploads
volumes:
  uploads:
  mongodata:
